matrix:
  - name: markdown
    sources:
      - context: markdown
        src: "src/**/*.md"
        default_encoding: utf-8
    aspell:
      lang: en
      d: en_US
    hunspell:
      d: en_US
    pipeline:
      - name: pyspelling.filters.markdown
        markdown_extensions:
          - pymdownx.superfences
          - pymdownx.highlight
          - pymdownx.tabbed
          - admonition
          - toc
      - name: pyspelling.filters.html
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - code
          - pre
      - pyspelling.filters.url
