site_name: Van Cooldown
site_description: Documentation for the van-cooldown project covering hardware, firmware, and software
site_author: Fabien Meyer
site_url: https://fabienmeyer.github.io/van-cooldown/

repo_name: FabienMeyer/van-cooldown
repo_url: https://github.com/FabienMeyer/van-cooldown

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
  - pymdownx.snippets:
      base_path: '..'
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic:
      mode: view
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: FabienMeyer
      repo: van-cooldown

extra_javascript:
  - https://cdn.plot.ly/plotly-latest.min.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FabienMeyer/van-cooldown
      name: GitHub Repository
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FabienMeyer
      name: GitHub Profile
  generator: false

copyright: >
  Copyright &copy; 2025 Fabien Meyer · 
  <a href="license/">MIT License</a> · 
  This site respects your privacy - no cookies, no tracking, no analytics

nav:
  - Van Cooldown:
      - Home: index.md
      - Contributing: contributing.md
      - Code of Conduct: code_of_conduct.md
      - Code Owners: codeowners.md
      - License: license.md
      - Privacy: privacy.md
  - Architecture: architecture/architecture.md
  - Hardware: hardware/hardware.md
  - Firmware: firmware/firmware.md
  - Software: software/software.md
