[project]
name = "van-cooldown-docs"
version = "0.1.0"
description = "Documentation for the van-cooldown project."
readme = "../README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-mermaid2-plugin",
]

[tool.uv]
dev-dependencies = [
    "vale",
]
