name: Documentation CI

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-ci.yml'
  push:
    tags:
      - 'v*'
    branches:
      - 'release/*'
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"
      
      - name: Install dependencies
        run: |
          cd docs
          uv sync
      
      - name: Setup Node.js for documentation tools
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install documentation linting tools
        run: |
          npm install -g markdownlint-cli
          # Install Vale
          wget -qO- https://github.com/errata-ai/vale/releases/latest/download/vale_*_Linux_64-bit.tar.gz | tar -xz -C /usr/local/bin
      
      - name: Lint documentation
        run: |
          cd docs
          # Check Markdown formatting
          markdownlint src/**/*.md
          # Check prose quality
          vale src/
          # Spell check
          uv run pyspelling
      
      - name: Build documentation
        run: |
          cd docs
          uv run mkdocs build --strict
      
      - name: Test documentation links
        run: |
          cd docs
          # Check internal links
          uv run linkchecker --check-extern site/
      
      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site
          path: docs/site/
      
      - name: Deploy to GitHub Pages
        if: github.event_name == 'release' || (github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/release/')))
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/site/
          enable_jekyll: false
          cname: van-cooldown-docs.example.com  # Optional: custom domain

  accessibility-check:
    name: Accessibility Check
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'release' || (github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/release/'))) || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Download documentation artifacts
        uses: actions/download-artifact@v4
        with:
          name: documentation-site
          path: docs/site/
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install accessibility tools
        run: npm install -g @axe-core/cli
      
      - name: Serve documentation locally
        run: |
          cd docs/site
          python -m http.server 8000 &
          sleep 3
      
      - name: Run accessibility tests
        run: |
          axe http://localhost:8000 --exit